version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: method_app
    ports:
      - "7887:7887"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    container_name: redis_cache
    ports:
      - "6379:6379"
